name: Actions Runner Controller Test
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    #runs-on: arc-runner-set
    runs-on: self-hosted
    steps:
    - run: echo "This job uses your scale set runners on K8S!"
    - run: echo "Happy coding FREEEE"
