name: Actions Runner Controller Test
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    #runs-on: arc-runner-set
    runs-on: self-hosted
    steps:
    - name: Print some messages
      run: |
        echo "This job uses your scale set runners on K8S!"
        echo "Happy coding"
      
    - name: Get Pod Info
      run: |
        echo "Fetching pod information..."
        echo "Hostname: $(hostname)"
        echo "Kernel Version: $(uname -r)"
        echo "Pod IP Address: $(hostname -i)"
        echo "CPU Info: $(lscpu | grep 'Model name')"
        echo "Memory Info: $(free -h)"
        echo "Disk Usage: $(df -h / | tail -n 1)"
      
